development:
  adapter: postgresql
  encoding: unicode
  database: taylor_development
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: taylor_test
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  database: taylor_production
  pool: 5
  username: taylor
  password:
